import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import copyFilePlugin from 'esbuild-plugin-copy-file';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const SANDBOX_DEST="/Users/vsun/Library/Mobile Documents/iCloud~md~obsidian/Documents/sandbox/.obsidian/plugins/obsidian-mov-support"
const PROD_DEST="/Users/vsun/Library/Mobile Documents/iCloud~md~obsidian/Documents/vsun-icloud/.obsidian/plugins/obsidian-mov-support"
const PROD_MOBILE_DEST="/Users/vsun/Library/Mobile Documents/iCloud~md~obsidian/Documents/vsun-icloud/.obsidian-ios/plugins/obsidian-mov-support"


const watch = (process.argv[3] === 'no-watch') ? false : true;

let dest;
let sourcemap;

switch(process.argv[2]){
	case 'prod':
		dest = PROD_DEST; 
		sourcemap = false;
		break;
	case 'prod-mobile':
		dest = PROD_MOBILE_DEST; 
		sourcemap = false;
		break;
	case 'sandbox':
		dest = SANDBOX_DEST; 
		sourcemap = 'inline';
		break;
	default:
		console.error(`unrecognized argument: valid ones are "prod", "prod-mobile", "sandbox"`);
		process.exit(1);
}

console.log(`esbuild "${process.argv[2]}" for dest: ${dest}`);

// const main = `${dest}/main.js`;
// const styles = `${dest}/styles.css`;
// const manifest = `${dest}/manifest.json`;

const copyConfig  = {};
copyConfig[`${dest}/main.js`] = './main.js';
copyConfig[`${dest}/styles.css`] ='./styles.css';
copyConfig[`${dest}/manifest.json`] = './manifest.json',

console.log(`copy config=`, copyConfig);

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...builtins
	],
	format: 'cjs',
	watch,
	target: 'es2016',
	logLevel: "info",
	sourcemap,
	treeShaking: true,
	outfile: 'main.js',
	plugins: [
		copyFilePlugin({ after: copyConfig})
	]
}).catch(() => process.exit(1));
